server:
  port: 80
  error:
    whitelabel:
      enabled: false


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_upkeep
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  web:
    resources:
      add-mappings: false